### Root
GET http://localhost:5000

### Get Users
GET http://localhost:5000/users

### Create User
POST http://localhost:5000/users
Content-Type: application/json

{
  "id": 3,
  "name": "Charlie3",
  "email": "charlie@example.com"
}